In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/weather_data (3).csv", parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [3]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [4]:
new_df = df.fillna(888)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04        888.0        9.0   Sunny
2 2017-01-05         28.0      888.0    Snow
3 2017-01-06        888.0        7.0     888
4 2017-01-07         32.0      888.0    Rain
5 2017-01-08        888.0      888.0   Sunny
6 2017-01-09        888.0      888.0     888
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [5]:
new_df = df.fillna({
    'temperature': 0 ,
    'windspeed': df["windspeed"].mean(),
    'event':'no event'
})
new_df

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-04          0.0        9.0     Sunny
2 2017-01-05         28.0        8.4      Snow
3 2017-01-06          0.0        7.0  no event
4 2017-01-07         32.0        8.4      Rain
5 2017-01-08          0.0        8.4     Sunny
6 2017-01-09          0.0        8.4  no event
7 2017-01-10         34.0        8.0    Cloudy
8 2017-01-11         40.0       12.0     Sunny

In [6]:
new_df=df.fillna(method="ffill")
new_df

/tmp/ipykernel_15963/1259950058.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=df.fillna(method="ffill")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [7]:
new_df = df.fillna(method="bfill")
new_df

/tmp/ipykernel_15963/200175317.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="bfill")

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [8]:
new_df = df.copy()
new_df['temperature'] = new_df['temperature'].fillna(new_df['temperature'].mean())
new_df['windspeed'] = new_df['windspeed'].fillna(new_df['windspeed'].mean())
print("data frame with nulls in numerical columns filled with their average")
new_df

data frame with nulls in numerical columns filled with their average

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         33.2        9.0   Sunny
2 2017-01-05         28.0        8.4    Snow
3 2017-01-06         33.2        7.0     NaN
4 2017-01-07         32.0        8.4    Rain
5 2017-01-08         33.2        8.4   Sunny
6 2017-01-09         33.2        8.4     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [9]:
new_df = df.copy()
new_df['temperature'] = new_df['temperature'].fillna(new_df['temperature'].mean())
new_df['windspeed'] = new_df['windspeed'].fillna(new_df['windspeed'].mean())

new_df.loc[(new_df['temperature'] <10) & (new_df['event'].isnull()), 'event'] ='snow'
new_df.loc[(new_df['temperature'] >30) & (new_df['event'].isnull()), 'event']= 'sunny'
print("data frame with 'event' columns update based on temperature condations")
new_df

data frame with 'event' columns update based on temperature condations

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         33.2        9.0   Sunny
2 2017-01-05         28.0        8.4    Snow
3 2017-01-06         33.2        7.0   sunny
4 2017-01-07         32.0        8.4    Rain
5 2017-01-08         33.2        8.4   Sunny
6 2017-01-09         33.2        8.4   sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [10]:
####  DROP NULL ####

In [11]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [12]:
new_df = new_df.dropna()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         33.2        9.0   Sunny
2 2017-01-05         28.0        8.4    Snow
3 2017-01-06         33.2        7.0   sunny
4 2017-01-07         32.0        8.4    Rain
5 2017-01-08         33.2        8.4   Sunny
6 2017-01-09         33.2        8.4   sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [13]:
neww_df = df
neww_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [14]:
new_df = neww_df.dropna()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [15]:
new_df = neww_df.dropna(how = 'all')
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [16]:
new_df = neww_df.dropna(thresh=3)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
4 2017-01-07         32.0        NaN    Rain
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [17]:
new_df = neww_df.dropna(thresh=2)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [18]:
####  DROPING BY CONDATION ####

In [19]:
new_df = neww_df[(neww_df['temperature'].notna()) & (neww_df['temperature'] != 0 ) ]
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
2 2017-01-05         28.0        NaN    Snow
4 2017-01-07         32.0        NaN    Rain
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [20]:
new_df = neww_df[(neww_df['temperature'].notna())& (neww_df['temperature']!='')]
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
2 2017-01-05         28.0        NaN    Snow
4 2017-01-07         32.0        NaN    Rain
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [21]:
df.loc[1 , 'temperature'] = 30
df.loc[3 , 'temperature'] = 32
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         30.0        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06         32.0        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [32]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_excel('/content/Sales Data - Copy (2) (1).xlsx', sheet_name='Sales Data')
df

,Order ID,Year,Month,Week number,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Client Segment,...,Product Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Total Sales Amount,Purchasing Price,Total Purchasing Amounts,Net Profit
0,CA-2016-152156,2020,Nov,46,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0,523.9200,157.17600,314.35200,209.56800
1,CA-2016-152156,2020,Nov,46,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0,2195.8200,402.56700,1207.70100,988.11900
2,CA-2016-138688,2020,Jun,25,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0,29.2400,8.77200,17.54400,11.69600
3,US-2015-108966,2020,Oct,42,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0,4787.8875,478.78875,2393.94375,2393.94375
4,US-2015-108966,2020,Oct,42,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0,35.7888,11.18400,22.36800,13.42080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112,CA-2016-137330,2020,Dec,50,2016-12-09,2016-12-13,Standard Class,KB-16585,Ken Black,Corporate,...,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.3400,7,0,1531.0000,36.20400,253.42800,168.95200
1113,US-2017-156909,2020,Jul,29,2017-07-16,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,...,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0,1219.0000,35.68600,71.37200,28.54880
1114,CA-2015-106320,2020,Sep,39,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0,1928.0000,522.31500,1566.94500,1566.94500
1115,CA-2016-121755,2020,Jan,3,2016-01-16,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,...,Office Supplies,Binders,Wilson Jones Active Use Binders,11.6480,2,0,1071.0000,7.57120,15.14240,3.49440
1116,CA-2016-121755,2016,Jan,3,2016-01-16,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,...,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.5700,3,0,1215.0000,54.34200,163.02600,108.68400

In [ ]:
####  Handling Duplicates  ####

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1117 entries, 0 to 1116
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order ID                  1117 non-null   object
 1   Year                      1117 non-null   int64
 2   Month                     1117 non-null   object
 3   Week number               1117 non-null   int64
 4   Order Date                1117 non-null   datetime64[ns]
 5   Ship Date                 1117 non-null   datetime64[ns]
 6   Ship Mode                 1117 non-null   object
 7   Customer ID               1117 non-null   object
 8   Customer Name             1117 non-null   object
 9   Client Segment            1117 non-null   object
 10  Country                   1117 non-null   object
 11  State                     1117 non-null   object
 12  Postal Code               1117 non-null   int64
 13  Region                    1117 non-null   object
 14  Product ID                1117 non-null   object
 15  Product Category          1117 non-null   object
 16  Sub-Category              1117 non-null   object
 17  Product Name              1117 non-null   object
 18  Sales Price               1117 non-null   float64
 19  Quantity                  1117 non-null   int64
 20  Discount                  1117 non-null   int64
 21  Total Sales Amount        1117 non-null   float64
 22  Purchasing Price          1117 non-null   float64
 23  Total Purchasing Amounts  1117 non-null   float64
 24  Net Profit                1117 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(5), object(13)
memory usage: 218.3+ KB

In [44]:
Duplicate_rows_df = df[df.duplicated()]
print('Duplicate rows except first occurrence based on all columns are:')
Duplicate_rows_df

Duplicate rows except first occurrence based on all columns are:

,Order ID,Year,Month,Week number,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Client Segment,...,Product Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Total Sales Amount,Purchasing Price,Total Purchasing Amounts,Net Profit
1006,CA-2017-100314,2017,Sep,39,2017-09-29,2017-10-05,Standard Class,AS-10630,Ann Steele,Home Office,...,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Recycled Envelopes",27.968,4,0,89.4976,18.1792,72.7168,16.7808
1007,CA-2017-100314,2017,Sep,39,2017-09-29,2017-10-05,Standard Class,AS-10630,Ann Steele,Home Office,...,Technology,Machines,Wasp CCD Handheld Bar Code Reader,336.510,3,0,1009.5300,201.9060,605.7180,403.8120
1008,CA-2015-146829,2015,Mar,11,2015-03-10,2015-03-10,Same Day,TS-21340,Toby Swindell,Consumer,...,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,1.112,2,0,2.2240,0.7784,1.5568,0.6672
1009,CA-2017-167899,2017,May,21,2017-05-21,2017-05-26,Standard Class,JG-15805,John Grady,Corporate,...,Furniture,Furnishings,Luxo Professional Magnifying Clamp-On Fluoresc...,520.050,5,0,2600.2500,364.0350,1820.1750,780.0750
1010,CA-2017-167899,2017,May,21,2017-05-21,2017-05-26,Standard Class,JG-15805,John Grady,Corporate,...,Office Supplies,Art,Bulldog Table or Wall-Mount Pencil Sharpener,17.970,3,0,53.9100,11.6805,35.0415,18.8685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112,CA-2016-137330,2020,Dec,50,2016-12-09,2016-12-13,Standard Class,KB-16585,Ken Black,Corporate,...,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340,7,0,1531.0000,36.2040,253.4280,168.9520
1113,US-2017-156909,2020,Jul,29,2017-07-16,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,...,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0,1219.0000,35.6860,71.3720,28.5488
1114,CA-2015-106320,2020,Sep,39,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0,1928.0000,522.3150,1566.9450,1566.9450
1115,CA-2016-121755,2020,Jan,3,2016-01-16,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,...,Office Supplies,Binders,Wilson Jones Active Use Binders,11.648,2,0,1071.0000,7.5712,15.1424,3.4944
1116,CA-2016-121755,2016,Jan,3,2016-01-16,2016-01-20,Second Class,EH-13945,Eric Hoffmann,Consumer,...,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0,1215.0000,54.3420,163.0260,108.6840

In [45]:
print('number of duplicate rows :' , len(Duplicate_rows_df))

number of duplicate rows : 85

In [46]:
print('total number of records:' , len(df))

total number of records: 1117

In [47]:
df = df.drop_duplicates().copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1032 entries, 0 to 1064
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order ID                  1032 non-null   object
 1   Year                      1032 non-null   int64
 2   Month                     1032 non-null   object
 3   Week number               1032 non-null   int64
 4   Order Date                1032 non-null   datetime64[ns]
 5   Ship Date                 1032 non-null   datetime64[ns]
 6   Ship Mode                 1032 non-null   object
 7   Customer ID               1032 non-null   object
 8   Customer Name             1032 non-null   object
 9   Client Segment            1032 non-null   object
 10  Country                   1032 non-null   object
 11  State                     1032 non-null   object
 12  Postal Code               1032 non-null   int64
 13  Region                    1032 non-null   object
 14  Product ID                1032 non-null   object
 15  Product Category          1032 non-null   object
 16  Sub-Category              1032 non-null   object
 17  Product Name              1032 non-null   object
 18  Sales Price               1032 non-null   float64
 19  Quantity                  1032 non-null   int64
 20  Discount                  1032 non-null   int64
 21  Total Sales Amount        1032 non-null   float64
 22  Purchasing Price          1032 non-null   float64
 23  Total Purchasing Amounts  1032 non-null   float64
 24  Net Profit                1032 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(5), object(13)
memory usage: 209.6+ KB

In [ ]:
####  Verification that the data has been dropped successfully  ####

In [48]:
Duplicate_rows_df= df[df.duplicated()]
Duplicate_rows_df

Empty DataFrame
Columns: [Order ID, Year, Month, Week number, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Client Segment, Country, State, Postal Code, Region, Product ID, Product Category, Sub-Category, Product Name, Sales Price, Quantity, Discount, Total Sales Amount, Purchasing Price, Total Purchasing Amounts, Net Profit]
Index: []

[0 rows x 25 columns]

In [ ]:
#### verification for the real df ####

In [49]:
print('total number of records:' , len(df))

total number of records: 1032

In [51]:
df.to_excel('/content/Sales Data - Copy (2) (1).xlsx' , sheet_name='Sales Data' , index = False)
from google.colab import files
files.download ('/content/Sales Data - Copy (2) (1).xlsx')

In [56]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Year_Month_Date'] = pd.to_datetime(
    df['Year'].astype(str) + '_' +
    df['Month'] + '_' +
    '01' ,
    format = '%Y_%b_%d'
)
print(df[['Year','Month' , 'Year_Month_Date']].head())
df.info()

   Year Month Year_Month_Date
0  2020   Nov      2020-11-01
1  2020   Nov      2020-11-01
2  2020   Jun      2020-06-01
3  2020   Oct      2020-10-01
4  2020   Oct      2020-10-01
<class 'pandas.core.frame.DataFrame'>
Index: 1032 entries, 0 to 1064
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order ID                  1032 non-null   object
 1   Year                      1032 non-null   int64
 2   Month                     1032 non-null   object
 3   Week number               1032 non-null   int64
 4   Order Date                1032 non-null   datetime64[ns]
 5   Ship Date                 1032 non-null   datetime64[ns]
 6   Ship Mode                 1032 non-null   object
 7   Customer ID               1032 non-null   object
 8   Customer Name             1032 non-null   object
 9   Client Segment            1032 non-null   object
 10  Country                   1032 non-null   object
 11  State                     1032 non-null   object
 12  Postal Code               1032 non-null   int64
 13  Region                    1032 non-null   object
 14  Product ID                1032 non-null   object
 15  Product Category          1032 non-null   object
 16  Sub-Category              1032 non-null   object
 17  Product Name              1032 non-null   object
 18  Sales Price               1032 non-null   float64
 19  Quantity                  1032 non-null   int64
 20  Discount                  1032 non-null   int64
 21  Total Sales Amount        1032 non-null   float64
 22  Purchasing Price          1032 non-null   float64
 23  Total Purchasing Amounts  1032 non-null   float64
 24  Net Profit                1032 non-null   float64
 25  Year_Month_Date           1032 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(5), int64(5), object(13)
memory usage: 217.7+ KB

In [59]:
df['Order Year'] = df['Order Date'].dt.year
df['Order_Month_NUM'] = df['Year_Month_Date'].dt.month
df['Order_Month_Name'] = df['Year_Month_Date'].dt.month_name()
df['Order_Quarter'] = df['Year_Month_Date'].dt.quarter
print(df[['Year_Month_Date','Order Year','Order_Month_NUM','Order_Quarter']].head())
print('extracted year , month(numerical) , month name and quarter:')
df.info()

  Year_Month_Date  Order Year  Order_Month_NUM  Order_Quarter
0      2020-11-01        2016               11              4
1      2020-11-01        2016               11              4
2      2020-06-01        2016                6              2
3      2020-10-01        2015               10              4
4      2020-10-01        2015               10              4
extracted year , month(numerical) , month name and quarter:
<class 'pandas.core.frame.DataFrame'>
Index: 1032 entries, 0 to 1064
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order ID                  1032 non-null   object
 1   Year                      1032 non-null   int64
 2   Month                     1032 non-null   object
 3   Week number               1032 non-null   int64
 4   Order Date                1032 non-null   datetime64[ns]
 5   Ship Date                 1032 non-null   datetime64[ns]
 6   Ship Mode                 1032 non-null   object
 7   Customer ID               1032 non-null   object
 8   Customer Name             1032 non-null   object
 9   Client Segment            1032 non-null   object
 10  Country                   1032 non-null   object
 11  State                     1032 non-null   object
 12  Postal Code               1032 non-null   int64
 13  Region                    1032 non-null   object
 14  Product ID                1032 non-null   object
 15  Product Category          1032 non-null   object
 16  Sub-Category              1032 non-null   object
 17  Product Name              1032 non-null   object
 18  Sales Price               1032 non-null   float64
 19  Quantity                  1032 non-null   int64
 20  Discount                  1032 non-null   int64
 21  Total Sales Amount        1032 non-null   float64
 22  Purchasing Price          1032 non-null   float64
 23  Total Purchasing Amounts  1032 non-null   float64
 24  Net Profit                1032 non-null   float64
 25  Year_Month_Date           1032 non-null   datetime64[ns]
 26  Order Year                1032 non-null   int32
 27  Order_Month_NUM           1032 non-null   int32
 28  Order_Quarter             1032 non-null   int32
 29  Order_Month_Name          1032 non-null   object
dtypes: datetime64[ns](3), float64(5), int32(3), int64(5), object(14)
memory usage: 237.8+ KB